### ISSUE TITLE
issu

### ISSUE THREAD

**Issue by IWantToBeBlue** [Scruffydrew/Forza-Horizon-5-Auction-House-Sniper#1]
when it dont fin the buy thing it stops

**Comment by IWantToBeBlue** [comment]
and it cant buy cars for you it ovly bet on the cars

**Comment by Scruffydrew** [comment]
what do you mean by buy thing also would you mind telling me what you have the resolution set to ingame

**Comment by Scruffydrew** [comment]
Also would you mind running the latest pre-release and sending me back the file it creates, it should be called logfile.log

**Comment by IWantToBeBlue** [comment]
i have tried with 1920 x 1080 and 2560 x 1440

**Comment by IWantToBeBlue** [comment]
show it does not get the car it has bid for then it stops and it does not buy but it only bids

**Comment by IWantToBeBlue** [comment]
sorry it's been so long

**Comment by Scruffydrew** [comment]
sorry for the late reply but here is what i have my video setting set to
![image](https://user-images.githubusercontent.com/66156463/179148902-f300ab7e-f973-4d80-bd5f-93a39b3504f4.png)
Try setting it to this and see how it goes, also set the brightness to 50.
If that doesn't work let me know and i might have to jump on a call or something with you that way i can get you to show me what its doing so that i might be able to figure it out bc it seems to be working fine for me.

**Comment by Scruffydrew** [comment]
if it doesnt work heres my discord Scruffydrew#2909 , send me a friend request and we can work out a time where i can jump on a call with you or something and try to figure out why it isnt working.

**Comment by IWantToBeBlue** [comment]
![Skærmbillede 2022-07-15 142831](https://user-images.githubusercontent.com/95884925/179223007-569dbe0d-fa07-46b4-8da9-026c28ef005d.png)

**Comment by IWantToBeBlue** [comment]
new issu

**Comment by IWantToBeBlue** [comment]
thank you for the help 
it works now, I dont know what did, so it work but i did
