### ISSUE TITLE
Script Stays at "Search Function"

### ISSUE THREAD

**Issue by Perytron** [Scruffydrew/Forza-Horizon-5-Auction-House-Sniper#5]
Hello **Scruffydrew**!

First of all, thank you very much for developing such a promising tool!

However, I cannot get to run it properly. The overlay is appearing, then it automatically goes from **_Auction House_** to **_Search Function_**, however, after that, it does not continue whatsoever.

I am on a 60hz 1920x1080 monitor and FH5 is set to **German**. Could the language setting be the problem?

It endlessly prints _Line: 66_ to the log file:
```
Welcome to the Forza Auction House Sniper Bot
Starting program
Forza Horizon 5
Line: 50
Line: 58
Line: 66
Line: 66
Line: 66
Line: 66
Line: 66
```

**Comment by Scruffydrew** [comment]
give the latest release a go and let me know if it works with the language set to German

**Comment by BE3dARt** [comment]
Hello again **Scruffydrew**! 

Thank you for the quick fix. It successfully bought a car from the auction house. However, it would not claim the car the first time it tried. Then again, later, it would bid on a car instead of buying it. 

Just for the reference, on which resolution are you developing?

**Comment by Scruffydrew** [comment]
at the moment the program doesn't actually claim the car, I will work on implementing that now and I will look into fixing the problem with it bidding on the car instead of buying it out, thanks for letting me know

as to your question about the resolution, here are my current settings but the frame rate shouldn't matter, the only thing that might is brightness and if you have a hdr display
![image](https://user-images.githubusercontent.com/66156463/182509551-27236428-60de-428c-bb11-80817c31b09e.png)

**Comment by Scruffydrew** [comment]
I've just uploaded a new version test that one out and let me know if there are any issues
