### ISSUE TITLE
Programm does not work 

### ISSUE THREAD

**Issue by BlaZe989o** [Scruffydrew/Forza-Horizon-5-Auction-House-Sniper#7]
Hi
It only shows 
Line: 50
Line: 50
Line: 50
Line: 50
Line: 50
I have a 144hz 1440p Monitor an my Game language is German
but It works if I set the resulution in Windows to 1080p and In game to 900

**Comment by Scruffydrew** [comment]
does it work when you set windows resolution to 1080p and game resolution to 1080p?
pretty sure i wrote the program to only work for 1080p monitors but i do have an idea as to how to make it work for various resolutions, i just dont know if they will actually work.
as for the game language im pretty sure for the most part i already modified the program to work no matter the language, but didnt do any extensive testing in regards to that, pretty sure i only tested it with german so that shouldn't be an issue, ill have to look into modifying the program to work with various resolutions tho so ill work on that and ill get back to you.

**Comment by Scruffydrew** [comment]
i've uploaded a new version that should work with your monitor resolution, if it still doesnt work you might need to set the ingame resolution to 1080p.
let me know how it goes

**Comment by BlaZe989o** [comment]
Yes It workes now thank you but I found out another bug after collecting a car the programm doesnt do something anymore until you press enter

**Comment by Scruffydrew** [comment]
Ok thanks for letting me know, I imagine that that might be a timing issue or something to do with where it is checking the pixels.
I'll have a look into it later as I was actually about to go to sleep, so when I wake up I'll see if I can fix that issue

**Comment by Scruffydrew** [comment]
would you be able to send me the log file that was created when running the program

**Comment by Scruffydrew** [comment]
i've uploaded a new release that might fix the issue that your having if it doesnt fix the issue please send the log file that the program generates, it will also help if you send a screenshot of when the program is getting suck
